### ISSUE TITLE
Implement Item delete and Item create

### ISSUE THREAD

**Issue by benicamera** [benicamera/SupplyManager#10]
# Tasks

- [ ] Create Item and add to list
- [ ] Remove Item from list
- [ ] Update view

## Create Item and add to list

- [ ]  Creation form (maybe with image select)
- [ ] Add to list

## Remove Item from list
- [ ] Swipe or long press
- [ ] Confirm question
