### ISSUE TITLE
Implement Different Units

### ISSUE THREAD

**Issue by benicamera** [benicamera/SupplyManager#5]
# Tasks

- [ ] Implement MoneyUnit class
- [ ] Implement VolumeUnit class
- [ ] Implement WeightUnit class

## Implement MoneyUnit class
The money unit class inherits from the unit class. Implement needed functionality.
For conversion rates use API
